before_install:
  - gem update --system
  - gem --version

language: ruby

rvm:
  - 2.0.0

gemfile: Gemfile

script: rspec spec

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml