before_install:
  - gem update --system
  - gem --version

language: ruby

rvm:
  - 2.0.0

gemfile: Gemfile

script: rspec spec

services:
  - mongodb

#before_script:
#  - psql -c 'create database cavy_test;' -U postgres
#  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
#  - RAILS_ENV=test bundle exec rake db:migrate --trace