version: '2'
services:
  web:
    build: .
    command: spec/dummy/bin/rails server -p 3000 -b 0.0.0.0 -e development
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'secret'
    volumes:
      - /srv/docker/cavy/postgres/data:/var/lib/postgresql/data
