development:
  adapter: postgresql
  encoding: unicode
  database: cavy_development
  host: localhost
  pool: 5
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: cavy_test
  host: localhost
  pool: 5
  password:
#
#production:
#  adapter: postgresql
#  encoding: unicode
#  database: cavy_production
#  host: localhost
#  pool: 5
#  password:
