default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: cavy
  password: secret

development:
  <<: *default
  database: cavy_development

test:
  <<: *default
  database: cavy_test

production:
  <<: *default
  database: cavy_production
