development:
  adapter: postgresql
  encoding: unicode
  database: cavy_development
  host: db
  user: postgres
  password: secret
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: cavy_test
  host: db
  user: postgres
  password: secret
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: cavy_production
  host: localhost
  user: postgres
  pool: 5
  password:
