development:
  adapter: postgresql
  encoding: unicode
  database: cavy_development
  host: localhost
  pool: 5
  username: cavy
  password: secret
test:
  adapter: postgresql
  encoding: unicode
  database: cavy_test
  host: localhost
  pool: 5
  username: cavy
  password: secret
#
#production:
#  adapter: postgresql
#  encoding: unicode
#  database: cavy_production
#  host: localhost
#  pool: 5
#  password:
