development:
  adapter: postgresql
  encoding: unicode
  database: cavy_development
  host: localhost
  user: cavy
  password: secret
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: cavy_test
  host: localhost
  user: cavy
  password: secret
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: cavy_production
  host: localhost
  user: cavy
  pool: 5
  password: secret
